name: Generate Snake

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: github-snake.svg
